// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdfGfOijGVrxibH5AuCGSfxLl2AvjeY-8',
    appId: '1:840658812343:web:df6c947d005cce76fffc32',
    messagingSenderId: '840658812343',
    projectId: 'book-hunter-7536a',
    authDomain: 'book-hunter-7536a.firebaseapp.com',
    storageBucket: 'book-hunter-7536a.firebasestorage.app',
    measurementId: 'G-808GKS5ZZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy6eTYJ4HDkAAtZ-2reOd2GCiaZK4secs',
    appId: '1:840658812343:android:2ba4950b58d96bd1fffc32',
    messagingSenderId: '840658812343',
    projectId: 'book-hunter-7536a',
    storageBucket: 'book-hunter-7536a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIlLfmpShoUJEx8GD7TR-5OleQY6kxKc',
    appId: '1:840658812343:ios:f709acc48332b8eefffc32',
    messagingSenderId: '840658812343',
    projectId: 'book-hunter-7536a',
    storageBucket: 'book-hunter-7536a.firebasestorage.app',
    iosBundleId: 'com.example.bookHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIlLfmpShoUJEx8GD7TR-5OleQY6kxKc',
    appId: '1:840658812343:ios:f709acc48332b8eefffc32',
    messagingSenderId: '840658812343',
    projectId: 'book-hunter-7536a',
    storageBucket: 'book-hunter-7536a.firebasestorage.app',
    iosBundleId: 'com.example.bookHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdfGfOijGVrxibH5AuCGSfxLl2AvjeY-8',
    appId: '1:840658812343:web:a07d383d365c607afffc32',
    messagingSenderId: '840658812343',
    projectId: 'book-hunter-7536a',
    authDomain: 'book-hunter-7536a.firebaseapp.com',
    storageBucket: 'book-hunter-7536a.firebasestorage.app',
    measurementId: 'G-VVVZ6EN7JJ',
  );
}
